
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/unit-test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#logging:
#  path: calsspath:logback.xml

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

debug: true